wandb_version: 1

'data:':
  desc: null
  value: C4 200M
model:
  desc: null
  value: baseModelV1
files_taken:
  desc: null
  value: 1
n_rows:
  desc: null
  value: 1000
latent_dim:
  desc: null
  value: 256
epoch:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700204465.001835
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
